# LXC hosting jellyfin
# /etc/pve/lxc/101.conf

arch: amd64
cores: 1
features: nesting=1
hostname: jellyfin
memory: 512
mp0: /mnt/media,mp=/mnt/media
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.100.1,hwaddr=BC:24:11:1B:03:2B,ip=192.168.100.2/24,type=veth
ostype: debian
rootfs: local:101/vm-101-disk-0.raw,size=8G
swap: 512
unprivileged: 1