# LXC hosting qbittorrent and arr* stack
# Found in host /etc/pve/lxc/100.conf

arch: amd64
cores: 2
features: nesting=1
hostname: qbit-arr
memory: 1024
mp0: /mnt/media,mp=/mnt/media
net0: name=eth0,bridge=vmbr0,firewall=1,gw=192.168.100.1,hwaddr=BC:24:11:0C:F5:C7,ip=192.168.100.100/24,type=veth
ostype: debian
rootfs: local:100/vm-100-disk-0.raw,size=400G
swap: 1024
unprivileged: 1
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir